# Generated by Django 4.1.7 on 2023-02-26 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0002_alter_department_options_customuser_middle_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='phone_number_mobile',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='phone_number_work',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
