# Generated by Django 4.1.7 on 2023-02-26 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0004_alter_customuser_phone_number_mobile_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='department',
            options={'verbose_name': 'Отдел', 'verbose_name_plural': 'Отделы'},
        ),
    ]
