# Generated by Django 4.0.5 on 2023-03-03 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0006_alter_customuser_department'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'ordering': ('id',)},
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='is_staff',
        ),
    ]
