# Generated by Django 4.0.5 on 2023-03-03 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0008_customuser_is_staff'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
    ]
